### ISSUE TITLE
Adding OnmiboxAppLauncher to Taskbar

### ISSUE THREAD

**Issue by ExplEngineer** [breeswish/OmniboxAppLauncher#1]
I am not sure how I did it, but this is on the Taskbar on one of my other computers, but I don't have any idea how it got there (I think it was put there when I updated to Chrome) but I don't know how to get it added on to the task bars on another Windows 7  computer and one that is running Win v8.1. Both are running chrome, and I am pretty sure that it is added on to the other Win7 computer, don't see it on the Win v8.1 at all, Can you give me some instructions (remembering that I am about as computer illiterate & dumb as can be, and so old school that I spent my career dictating my work to a secretary who took steno, my car phone was an old IMTS (I do miss the range that unit had) and I have to send my new Blackberry to my son when I get one so that he can undo all the damage that the kids at the ATT store have done and set it up just as he did the old one) that I can follow, written at the skill level described herein (v.a.)? I would appreciate it if I could put it on those, and my other computers when they come in, as it is one of the very few new things that I have learned to make work for me, and that makes it helpful, unlike some of the other new stuff my son put in my new phones to "make life easier for me(??)". And, it would be a big bonus If you could tell me how to add the apps I want to the launcher (not just have to accept whatever is there, and how to get them in the order I would like to be able to use them in. Yoo will have earned the eternal gratitude of an old man if you could actually write instructions that I understand how to use, and actually makes something on the computer that really does save dime and help me out. Doc (& the Lads)

**Comment by breezewish** [comment]
Hello, are you looking for this?

https://chrome.google.com/webstore/launcher

**Comment by ExplEngineer** [comment]
Yes, Thanks

Dr. Stephen B. Spies, M.D., Pharm., Psy.D., Ph.D.
Certified Fire Investigator
Certified Explosives Specialist
Polygraph Examiner
Judge Emeritus - Sachse, Texas

Explosives Engineering Technologies
The Institute of Criminalistics & the Forensic Sciences

Legal Notice: This message does not constitute legal or other professional advice, nor does it create an Attorney/Client, or other confidential or fiduciary relationship between the sender and/or any other party

Confidentiality Notice: This e-mail (including attachments) is covered by the Electronic Communications Privacy Act, 18 U. S. C., Sections 2510-2521, and is intended only for the person or entity to which it is addressed, and may contain confidential or privileged material. Any unauthorized review, use, disclosure, dissemination, copying, forwarding or distribution is prohibited. If you are not the intended recipient contact the sender by reply e-mail and destroy all copies of the original message. If you are the intended recipient but do not wish to receive communications through this medium please so advise the sender immediately.

Electronic Transmission Security Notice: Email transmission cannot be guaranteed to be secure or error-free. The sender does not accept liability for any errors or omissions in the contents of the message that arise as a result of its electronic (e-mail) transmission.
©2011 - Dr. Stephen B. Spies  

-----Original Message-----
